import = ["/Users/raulferrandopla/.config/alacritty/themes/gruvbox-dark.toml"]

[font]
size = 14.0


[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
